name: hudra
description:
  Breviary of the complete liturgical cycle according to the Holy Church of the East
  Chaldeans & Assyrians.

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.2
  http: ^1.2.2
  paged_vertical_calendar: ^1.1.8
  motion_toast: ^2.11.0
  intl: ^0.19.0
  getwidget: ^4.0.0
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.2.2
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  flutter_launcher_icons: ^0.13.1
  fimber: ^0.7.0
  connectivity_plus: ^6.0.5
  pretty_http_logger: ^1.0.4
  get_storage: ^2.1.1
  quill_html_editor: ^2.2.8
  delta_to_html: ^0.2.2
  flutter_html: ^3.0.0-beta.2
  sqflite: ^2.3.3+1
  path: ^1.9.0
  fullscreen_window: ^1.0.4
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "Assets/launch_icon/Group 178@2x.png"
  adaptive_icon_background: "#2b2223"
  #  adaptive_icon_foreground: "Assets/launch_icon/playstore.png"
  min_sdk_android: 19 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "Assets/launch_icon/Group 178@2x.png"
    adaptive_icon_foreground: "Assets/launch_icon/playstore.png"
  #    background_color: "#hexcode"
  #    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "Assets/launch_icon/Group 178@2x.png"
    adaptive_icon_foreground: "Assets/launch_icon/playstore.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  generate: true
  uses-material-design: true
  assets:
    - Assets/Icons/vuesax-linear-arrow-left.svg
    - Assets/Icons/Group 83.svg
    - Assets/Icons/Group 26.svg
    - Assets/Icons/book(1).svg
    - Assets/Icons/setting-2(1).svg
    - Assets/Icons/book.svg
    - Assets/Icons/vuesax-linear-maximize-4.svg
    - Assets/Icons/moon.svg
    - Assets/Icons/trash.svg
    - Assets/Icons/vuesax-linear-export.svg
    - Assets/Icons/global(1).svg
    - Assets/Icons/search-normal.svg
    - Assets/Icons/Vector.svg
    - Assets/Icons/vuesax-bold-moon.svg
    - Assets/Icons/Vector(1).svg
    - Assets/Icons/vuesax-linear-book-saved.svg
    - Assets/Icons/Group 8.svg
    - Assets/Icons/export.svg
    - Assets/Icons/Group 139.svg
    - Assets/Icons/timer(1).svg
    - Assets/Icons/setting-2.svg
    - Assets/Icons/heart(1).svg
    - Assets/Icons/calendar.svg
    - Assets/Icons/_Glyphs - Quick Action - Book.svg
    - Assets/Icons/heart.svg
    - Assets/Icons/notification.svg
    - Assets/Icons/timer.svg
    - Assets/Icons/calendar(1).svg
    - Assets/Icons/arrow-circle-right.svg
    - Assets/Icons/arrow-circle-left.svg
    - Assets/Icons/global.svg
    - Assets/Icons/Path 3684.svg
    - Assets/Icons/dove.svg
    - Assets/Icons/dove (1).svg
    - Assets/Images/crossDark.png
    - Assets/Images/crossError.png
    - Assets/Images/crossLight.png
    - Assets/Images/image1.png
    - Assets/launch_icon/Group 178@2x.png
    - Assets/launch_icon/playstore.png
    - Assets/info/CAPNI.jpeg
    - Assets/info/OAOC Logo.jpeg
    - Assets/info/info.svg
    - Assets/info/info filled.svg
    - Assets/info/ELKB.jpg
    - Assets/info/Diocese of Baghdad of the Assyrian Church of the East.jpg
    - Assets/info/Beirut in.jpg
    - Assets/info/Christian Aid Program Logo.svg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
