// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_50xq0hewyk7KN1hYJ-IBysC8xXR1YJ4',
    appId: '1:996608503939:web:fe9038cb7035ddf8002bb6',
    messagingSenderId: '996608503939',
    projectId: 'hudra-project',
    authDomain: 'hudra-project.firebaseapp.com',
    storageBucket: 'hudra-project.appspot.com',
    measurementId: 'G-YGYDYF63NG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxomasiqoVjVpoT_uBBMwjFBJwkOfKECQ',
    appId: '1:996608503939:android:3a0631cbc6545e93002bb6',
    messagingSenderId: '996608503939',
    projectId: 'hudra-project',
    storageBucket: 'hudra-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_SLgvMw7WFc68Y9QjTvrwHWqZ9toYknQ',
    appId: '1:996608503939:ios:9ac9b31cd1eba8d8002bb6',
    messagingSenderId: '996608503939',
    projectId: 'hudra-project',
    storageBucket: 'hudra-project.appspot.com',
    iosClientId: '996608503939-7da4mphkiq29kg98jl69pmh8tvmn8l2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.hudra_mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_SLgvMw7WFc68Y9QjTvrwHWqZ9toYknQ',
    appId: '1:996608503939:ios:9ac9b31cd1eba8d8002bb6',
    messagingSenderId: '996608503939',
    projectId: 'hudra-project',
    storageBucket: 'hudra-project.appspot.com',
    iosClientId: '996608503939-7da4mphkiq29kg98jl69pmh8tvmn8l2e.apps.googleusercontent.com',
    iosBundleId: 'com.example.hudra_mobile',
  );
}
